stages:
  load_data:
    cmd: python src/load_data.py --config_file params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/wine_raw.csv
