base:
  project: winequality
  random_state: 42
  target_col : TARGET

data_source:
  s3_source: data_given/winequality.csv

load_data:
  raw_source: data/raw/wine_raw.csv

split_data:
  train_path: data/processed/winequality_train.csv
  test_path: data/processed/winequality_test.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

report:
  scores: report/scores.json

model_dir: saved_models